{% set version = "1.1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-kernelknn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/KernelKnn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/KernelKnn/KernelKnn_{{ version }}.tar.gz
  sha256: faed5c523cf9cb2f2476b268a9bd701af852d715a1dd257b1fce0345af3f764e

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.5
    - r-rcpparmadillo
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  run:
    - r-base
    - r-rcpp >=0.12.5
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('KernelKnn')"           # [not win]
    - "\"%R%\" -e \"library('KernelKnn')\""  # [win]

about:
  home: https://github.com/mlampros/KernelKnn
  license: MIT
  license_file: LICENSE
  summary: Extends the simple k-nearest neighbors algorithm by incorporating numerous kernel functions and a variety of distance metrics. The package takes advantage of 'RcppArmadillo' to speed up the calculation of distances between observations.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
