travis:
  secure:
    BINSTAR_TOKEN: hXjqdi7GK6punNiE13ViGni25WYrpnU2l3X9hdr/reiiRJp9UgQcEQ5puhaLRy/vW3ygCEDCpJxvymJI/upArDEef0PA3lXD9MykefBza7fID+ZONea1Fs7/5El7BHdoj/qzaey073SqzDeNSWCALEssGFGrKe+qGw3SbduECUsQq0tRpIEHyhowIwegISdSIqktXDgQgjcpdCijUCWR3ewWtkkI5v1jQcvDv4uMrXHWCGxV2/h+MdjwbVuwXyIZK5+hO6bJBVryGGaIIxs5kDbn6Ovc7FR5ELZXdwVr6bRRntYVOTexQYzeiDYJ11MYMZJ0CSqUvaa8RMATRAUdRoZev8Rk2tJP7ZO2wY1HLVzM13aVY603VSaXiKD+BnxszSshV1ejDUa73m6Mp+0vxmDso14aKpnRVZSY/wju2x9k5MWM7bFXTPl0eJeL0vF7dfC9BRN6+pTVzsq/uQAcqjzuGc7e+ArDlnzfSQEdcnET7lYhFtOf5cyk8s3dvmPsG4ah7NNzfkgXnjMFAmAc4mtkLzTUzXlhOFKewcKxk9/9OaNBxLrAjx207P2P/ncbVfF7tv4p/6UoNv6vZutSNCHcK6zEHyqkrepMZ0Q/A62CTWSBmqbsdxx/zMUgfQOoqlkOgWkUgQX0iLA1JzFDHbNWqc8JvgSiLKigvyXqdN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
