appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: g6MIO5kGG4i/Q8IszqWbyEY4vbvkfVbkUZdz0CoQP+LuvtXj2V6MBKC4Bi0zC3RK1EeN2rj7zhN4pyDsgadBgoAvzE362Amf8kGpNr+cCTf+XBKyuk/WX418+q2UGxJ49K+yT2I/kwqOGLmHaJkPhHTfLy4FBj+gYqxm2BjF9/cob/PH2Zcq6USyVZijoy2yPVkyVrIMY29fEC6miXYicB3jL2t0TwLInGzKSmudtpYgetGZ5aiddT2IVuQkqOpP4+AGjSTeAv7u+XG6R8e1Kjdvyf4sZOEWt72TPsMBWqta3AoWQae9sHV5x45/MS0WwIzFFwuQNd9dTmm5EqLMoZ+3VWFI8b4qW75u9KOdagumZtas//mZMxRYg7oxzUMhJld1+n9oQu7t8//Mlw2zAobtY5yIuSF1HcaDRIHd615oLRtj2Nu+aZ5Aoxww2azJGGUr1/EgWqavWKCUvooB+mopRO1woVbkV/umcMdCVSPtGrLwxT38q8jDCiCLWbk3IcbUQ1as9AOGp5VyNW8YyGURlRQMwU1CqppkdD0kJee0CQOAOp5efeTUAi0WT0M9Mzhs7ji9wj0+iVdRZOJB3ljmRMct/cuy5QPInRfcSvs1XDgfnojk0ujSIUy7w/R1k49ttkuhH8dgN0SqMiwDsdDsi8XYj0vHJI8kgHNtU88=}
