travis:
  secure:
    BINSTAR_TOKEN: E514ppzSk0R92Z+m3gfDEF9N65SBh3VxKL1cufFfmLSzrlFVM3C7k0YZAWIzDvsAqN8f1QqFDk/Tu/zupvG/QIrAjsHvNFs6/ZsTtQCnql2KloqmoIeeuGYbKN4xA/DAnkm34M9uCmctiTq/pCdt28Gt4PKz2nvkrRvCxiggJkypvz5SIRgx/W6oZ2eKwIoU3O6QQEV2AITfm4M2leS59cCZ2KUCtQ1oQJiicxL2bQV/tRl57kW+VN/aurinsZlyHWz//P7sI/qvRaC9zdzmQN5tnl+ph2X7Y80pjLQGGruYVb5hG+r2u6DhjZQ1tfgdhLJD20HmYh9JYhfkN+a6tsjZu0HmRWnXlTD2ZwTbxGWOI80rhFf4Coy5B/dMepVn5PCjRX11afw4mtjew0QHGP/Ji8rHvV59JvSsJ+RvrmWtZthJzkBt2u8G+HMNs1XZjTF228Q9cVTdJfqLCcyG/MkpbxGaE+dOFolAZoDEspvQFpQiErlJ9SqriK1S5HFdN0R7Y8VpgtOPPHeIJuY3U+B0cbmQ50AWKZAce56GlTOK8/5FncyrPa1xyQAieJ71tEms3nCOIZZefq05GsVf7gQJDIU8KN3gF8EODStbvhlEjQmwZnPt6FAXbbNAn4Ilm9QdjHJ9HIgLDfQqDE9hax6OJZaF3eNY++GWoJLlypY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
